  113-refactor-checkedinattendees-signedupattendees[m
  12-us-020101-attendee-checks-into-event-by-scanning-qr-code[m
  120-remove-sign-up-on-start-create-loading-activity-to-immediately-redirect-to-homepage[m
  131-event-maps-attendee-check-in-maps[m
  138-us-010501-as-an-organizer-i-want-to-track-real-time-attendance-and-receive-alerts-for-important-milestones[m
  145-attendee-limit-is-optional[m
  15-us-010501-track-real-time-attendance-and-receive-alerts-for-milestones-2[m
* [32m175-dependency-injection-for-controllers[m
  20-us-030201-user-geolocation-enablingdisabling[m
  24-us-010102-reuse-existing-qr-code[m
  31-us-011101-organizer-optionally-limits-the-number-of-attendees-for-their-event[m
  42-firebase-filter[m
  5-us-010101-create-new-event-generate-a-unique-qr-code[m
  57-refactor-app-design-using-mvc[m
  8-us-010401-organizer-can-upload-event-poster[m
  9-us-020401-attendee-can-view-event-details-announcements-in-app[m
  DeviceIDBranch[m
  demo_hotfix[m
  main[m
  main_fix_user[m
  main_user_fix[m
  master[m
  qr-code-generation[m
  qr_code_scanner[m
